#12 issue solved - Changes done in the UI of  home page better user Interaction.
Harshdev098/Research-Nexas pull request #170
Opened 2024-10-16 15:28 UTC by SoumyaU25

## 📋 Description

## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #

## 📸 Screenshots (if applicable)

<img width="946" alt="r1" src="https://github.com/user-attachments/assets/4911d916-415d-4a98-ab5d-46fc4b54e1aa">
<img width="944" alt="r3" src="https://github.com/user-attachments/assets/6de9fafe-0e42-45f1-a578-30971dec4377">
<img width="941" alt="r4" src="https://github.com/user-attachments/assets/4c57fb02-2d43-4840-90d4-faacf1c88f2d">

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

2024-10-16 18:25 UTC, Harshdev098 requested changes
Is something wrong with this,
![image](https://github.com/user-attachments/assets/3b18c1bb-8c62-4d45-8c9c-973b05a3e34c)

Please increase the font-size of the navbar lists and the minimize the padding and side margin

2024-10-16 18:35 UTC, SoumyaU25 commented
Okay @Harshdev098 I'll do that

2024-10-17 06:37 UTC, SoumyaU25 commented
Hello @Harshdev098 I have done the changes . Please Check it out.

2024-10-17 08:13 UTC, Harshdev098 commented
Are the background image that you have set in the screenshot is not working 

![image](https://github.com/user-attachments/assets/4beb8823-440a-49ae-adc9-0ae0b8693333)

2024-10-17 09:36 UTC, SoumyaU25 commented
@Harshdev098 actually it's working fine at my end, I have set the right path for it.
<img width="943" alt="r5" src="https://github.com/user-attachments/assets/899f5836-2440-42d5-b00f-9bbd0052597d">

2024-10-17 16:29 UTC, Harshdev098 requested changes

2024-10-17 16:29 UTC, Harshdev098 commented on public/css/main_page_style.css
> +    background-image: linear-gradient(rgba(8, 23, 82, 0.75), rgba(30, 2, 30, 0.75)), url('public/images/calm.jpg');
edit the url with this `../images/calm.jpg`

2024-10-17 16:29 UTC, Harshdev098 commented on public/main_page.html
> +            <input type="text" placeholder="Search...">
Increase the input size of search box something like 20vw

2024-10-17 16:29 UTC, Harshdev098 commented on public/main_page.html
> +                 title="View Notifications"><i id="firsticon" class="fa-sharp fa-regular fa-bell"
The notification btn is not working as expected onmouseover and onmouseout properties

2024-10-17 18:11 UTC, SoumyaU25 commented
@Harshdev098 I have done all the changes as you said
changed the path for background image [x]
the input size of search box is increased about 22vw. [x]
The notification btn is working fine now. [x]
<img width="941" alt="r6" src="https://github.com/user-attachments/assets/42617866-6c14-4eea-a21a-c055d98818ad">

2024-10-17 18:30 UTC, Harshdev098 commented
@SoumyaU25 Delete the .vscode folder

2024-10-17 18:33 UTC, SoumyaU25 commented
Okay @Harshdev098

2024-10-17 18:36 UTC, SoumyaU25 commented
Done @Harshdev098

2024-10-17 19:15 UTC, merged