Solved Visibility of showing papers while allotment
Harshdev098/Research-Nexas pull request #171
Opened 2024-10-16 15:30 UTC by ygowthamr

# Fix: Visibility of Paper Details During Allotment

## Description
This PR ensures paper details remain accessible during the allotment process by improving UI behavior.

Fixes #135

@Harshdev098 
Pls give me gssoc-extd,hacktoberfest-accepted,level2 for this pull request

2024-10-16 15:37 UTC, ygowthamr commented
@Harshdev098 
Give me labels like gssoc-extd,hacktoberfest-accepted,level2 and merge my pr

2024-10-16 18:06 UTC, Harshdev098 requested changes
Don't just add the scrollTo method. If the allotment page become longer the user have to scroll down to see their left research papers
You can have a reference to #149

2024-10-17 02:33 UTC, ygowthamr commented
@Harshdev098 
Ok, I will update it.

2024-10-17 05:32 UTC, ygowthamr commented
@Harshdev098 
I have updated the code please check and merge my PR

2024-10-17 07:19 UTC, Harshdev098 requested changes

2024-10-17 07:19 UTC, Harshdev098 commented on public/script/paper_allotment.js
> +      window.scrollTo(0, 0);
remove this line because it scrolls the user to top

2024-10-17 07:54 UTC, ygowthamr commented on public/script/paper_allotment.js
> +      window.scrollTo(0, 0);
done

2024-10-17 08:13 UTC, merged