Added Update student profile feature in student dashboard
Harshdev098/Research-Nexas pull request #222
Opened 2024-10-19 14:27 UTC by ygowthamr

**What i have done: **

 - Added Update student profile feature in student dashboard
 
 @Harshdev098 
 Pls add labels like hacktoberfest,gssoc-extd,level3,etc.

2024-10-19 14:29 UTC, ygowthamr commented
@Harshdev098 
Pls review my pr and merge it.

2024-10-19 17:38 UTC, Harshdev098 requested changes

2024-10-19 17:38 UTC, Harshdev098 commented on backend/profile.js
> +let UserProfileID="";
dont't make new variable for user id

2024-10-19 17:38 UTC, Harshdev098 commented on backend/profile.js
> +    if (!UserProfileID) {
instead you can get the token from authorization and get the id of the user
this way it can be authenticated like we have done in display function

2024-10-19 17:40 UTC, ygowthamr commented
@Harshdev098 

Ok I will update it.

2024-10-20 07:21 UTC, ygowthamr commented
@Harshdev098 
Updated the code pls check and merge my pr

2024-10-20 11:08 UTC, ygowthamr commented
@Harshdev098 

Pls review and merge my pr

2024-10-20 13:59 UTC, Harshdev098 commented
I think its not working, whenever I save the updated profile it does not show the changes(while reloading also) figure it out
also add that whenever the user save the updation it would call the display function so that user can view their changes

2024-10-20 14:04 UTC, ygowthamr commented
@Harshdev098 
![image](https://github.com/user-attachments/assets/09036b81-c6b5-4ad4-a7da-9b38618bd59c)
As you can see in this image i am calling the function there is some problem in your side pls check.

2024-10-20 14:13 UTC, Harshdev098 commented
I have rechecked it its not working

2024-10-20 14:14 UTC, ygowthamr commented
@Harshdev098 

Can you send me any reference so that i understand what exactly happening.
In my pc it is working fine and the data is also updating.

2024-10-20 14:22 UTC, ygowthamr commented
[Update functionality is working.webm](https://github.com/user-attachments/assets/35967015-a2b6-4c64-940f-28c95a1e8682)

@Harshdev098 
In my pc with what code you have it is working video for reference it there above. once check dbserver.js where i added updateProfile route make sure that it is present and check the code in profile.js and dashboard.html is it matching with the code which i have commited.

2024-10-20 14:37 UTC, Harshdev098 commented
Its not fixing also the its not effecting the db data 

![image](https://github.com/user-attachments/assets/6a23271e-249f-478a-9167-bc10726fbe2b)

https://github.com/user-attachments/assets/5e0439fa-572b-4786-8011-7b4ed6a20c7d

2024-10-20 14:38 UTC, Harshdev098 commented
> Update.functionality.is.working.webm
> 
> @Harshdev098 In my pc with what code you have it is working video for reference it there above. once check dbserver.js where i added updateProfile route make sure that it is present and check the code in profile.js and dashboard.html is it matching with the code which i have committed.

its same

2024-10-20 14:39 UTC, ygowthamr commented
@Harshdev098 

Can you check the console what is the error you getting.

2024-10-20 14:51 UTC, Harshdev098 commented
It's not showing any error

2024-10-20 14:52 UTC, ygowthamr commented
@Harshdev098 

Did you add dbServer.js file

2024-10-20 14:54 UTC, Harshdev098 commented
It's already there with our changes

2024-10-20 14:55 UTC, Harshdev098 commented
Don't worry will figure it out just give me some time

2024-10-20 15:10 UTC, ygowthamr commented
@Harshdev098 
Pls try to resolve this error my tonight otherwise i will loose my rank in leaderboard

2024-10-20 15:30 UTC, ygowthamr commented
@Harshdev098 
Resolved conflicts pls check

2024-10-20 15:41 UTC, Harshdev098 commented
still its not working

2024-10-20 15:49 UTC, ygowthamr commented
@Harshdev098 
Is there any option so that i can connect to you via discord or any desk and resolve this issue?

2024-10-20 15:51 UTC, Harshdev098 commented
I am busy today because of my exams, we can discuss it tomorrow

2024-10-20 15:56 UTC, ygowthamr commented
@Harshdev098 
Can you try for last time.

2024-10-21 05:58 UTC, ygowthamr commented
@Harshdev098 
Sorry yesterday i forgot to update name and email id today i have added pls check and merge

2024-10-21 06:27 UTC, Harshdev098 approved these changes

2024-10-21 06:27 UTC, merged