fix: fixed all the broken links and formatted the file structure
Harshdev098/Research-Nexas pull request #295
Opened 2024-10-23 16:14 UTC by trinetra110

## 📋 Description

Fixed all the broken links and formatted the file structure of some files for proper understanding.

## 🔨 Changes Made

- Fixed all the broken links in 7 files
- Formatted the file structure in 7 files

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidelines mentioned in CONTRIBUTING.md.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #240 

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

2024-10-23 16:14 UTC, trinetra110 commented
@Harshdev098 I have made the required changes. Please review it and add the 'hacktoberfest', 'hacktoberfest-accepted', 'gssoc-ext' and 'level3' tags.

2024-10-24 02:20 UTC, Harshdev098 requested changes

2024-10-24 02:20 UTC, Harshdev098 commented on public/main_page.html
> +                    <li><a href="/#about_show">About</a></li>
remove this list item

2024-10-24 04:52 UTC, trinetra110 commented on public/main_page.html
> +                    <li><a href="/#about_show">About</a></li>
@Harshdev098 Which list item? Home, about, notification, or all of them?

2024-10-25 04:52 UTC, Harshdev098 commented on public/main_page.html
> +                    <li><a href="/#about_show">About</a></li>
only about

2024-10-25 06:50 UTC, trinetra110 commented on public/main_page.html
> +                    <li><a href="/#about_show">About</a></li>
Ok done

2024-10-25 06:51 UTC, trinetra110 commented
@Harshdev098 Conflict resolved and changes done. Please check.

2024-10-25 12:25 UTC, Harshdev098 commented
there are conflicts resolve them, please!

2024-10-26 03:53 UTC, Harshdev098 approved these changes

2024-10-26 03:53 UTC, merged