Logout functionality
Harshdev098/Research-Nexas pull request #296
Opened 2024-10-23 16:44 UTC by MrunalKashid02

## 📋 Description

## 🔨 Changes Made

- Added Logout functionality for stakeholder and student
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #237 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/c5d3643f-5313-400e-b7d4-e16bed221246

https://github.com/user-attachments/assets/6f32fb91-73c7-48a9-a23e-31cb64b9852a

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

2024-10-24 02:10 UTC, Harshdev098 requested changes

2024-10-24 02:10 UTC, Harshdev098 commented on public/dashboard.html
> +            localStorage.clear();
Instead of using clear function use removeItem for removing the token

2024-10-24 02:10 UTC, Harshdev098 commented on public/dashboard.html
> +            <p>Logout Successfully...</p>
Also increase the font-size of the message

2024-10-30 07:23 UTC, Harshdev098 commented
I have commited the changes, resolve branch conflicts!

2024-10-30 11:57 UTC, MrunalKashid02 commented on public/dashboard.html
> +            localStorage.clear();
I have check by updating branch someone already done this change

2024-10-30 11:58 UTC, MrunalKashid02 commented on public/dashboard.html
> +            <p>Logout Successfully...</p>
i have increase a font size and push the changes.

2024-10-30 12:05 UTC, Harshdev098 commented
The branch have conflicts resolve them please!

2024-10-30 12:44 UTC, MrunalKashid02 commented
I have resolve merge conflicts

2024-10-30 13:06 UTC, merged