Add a pop up dialog box for subscribing to newsletter done ! #306 ✨✨
Harshdev098/Research-Nexas pull request #312
Opened 2024-10-26 12:21 UTC by Subhajit-2023-44

Hello, PR
Add new feature - #306
Add a pop up dialog box for subscribing to newsletter done properly -

![Screenshot 2024-10-26 174107](https://github.com/user-attachments/assets/3867d274-9003-472e-a97c-8b32613f439f)

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

2024-10-26 12:22 UTC, Subhajit-2023-44 commented
@Harshdev098 done, Sir please merge my PR with level 3, If you check other projects, they are also giving level 3 for this..

![Screenshot 2024-10-26 112803](https://github.com/user-attachments/assets/efc8043d-f548-4982-85f7-7c8eecdf57a2)

You can check my code..

Thank you 🙏🏻

2024-10-26 15:42 UTC, Harshdev098 requested changes
Can you increase the form size to look as same as the image in the left

![Uploading image.png…]()

2024-10-26 15:46 UTC, Harshdev098 commented
@Subhajit-2023-44 

![Screenshot from 2024-10-26 21-11-20](https://github.com/user-attachments/assets/42c24513-700b-4302-9ab2-35534012ad98)

2024-10-26 16:27 UTC, Subhajit-2023-44 commented
> @Subhajit-2023-44
> 
> ![Screenshot from 2024-10-26 21-11-20](https://private-user-images.githubusercontent.com/118347330/380434626-42c24513-700b-4302-9ab2-35534012ad98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTk1ODksIm5iZiI6MTcyOTk1OTI4OSwicGF0aCI6Ii8xMTgzNDczMzAvMzgwNDM0NjI2LTQyYzI0NTEzLTcwMGItNDMwMi05YWIyLTM1NTM0MDEyYWQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNjE0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDE2NWY4NDBkZDI0NTViNTMwYmFlN2U0YjI5OGEzNjg3MmNhZjQ1MzcxMjNkY2Q2NTRmNzJiMTY3YTFhYTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B1Xr_ChZIii4qAuiZpq50zDJ7-L_w9TbjHiFoSHSpcY)

@Harshdev098 But sir, I have kept the same size of both part -

![image](https://github.com/user-attachments/assets/629edb7b-e3ab-413b-9d96-d5f036c7b87f)

2024-10-26 16:36 UTC, Harshdev098 commented
Will check it out and merge it by tomorrow

2024-10-26 16:39 UTC, Subhajit-2023-44 commented
> Will check it out and merge it by tomorrow

sir please check I have kept the same size of both part -


https://github.com/user-attachments/assets/bde5e7ad-f779-43e4-acc6-efdfb9ddcdae

2024-10-27 10:08 UTC, Subhajit-2023-44 commented
@Harshdev098 sir please merge my PR with level3 otherwise i can't able to another task..

2024-10-27 17:47 UTC, Subhajit-2023-44 commented
@Harshdev098 sir please merge my PR with level3 otherwise i can't able to another task..

2024-10-27 18:10 UTC, Harshdev098 commented
@Subhajit-2023-44 I am facing the same issue also after subscribing its not closing the display

https://github.com/user-attachments/assets/5095098e-ebae-4146-a489-9715f4edced6

2024-10-27 18:11 UTC, Harshdev098 commented
Also the previous issue persists in my firefox, its seems like it worked on chrome

2024-10-27 20:01 UTC, Subhajit-2023-44 commented
> Also the previous issue persists in my firefox, its seems like it worked on chrome

Ooo, but no problem in Chrome,  I don't use firefox, otherwise I would have checked it there too.  Sir check,  it is 100% zoomed in your browser or maybe it firefox website problem..

@Harshdev098 sir only two days left for the competition gssoc-ext.  Sir please🙏🏻  merge my PR with level3 otherwise i can't able to another task.. Thank You 🙏🏻

2024-10-28 03:00 UTC, Harshdev098 requested changes

2024-10-28 03:00 UTC, Harshdev098 commented on public/script/popup.js
> +      document.getElementById('popup').style.display = 'none';
Also check it, its not display none once it clicked on subscribe

2024-10-28 13:54 UTC, Subhajit-2023-44 commented on public/css/style.css
> +
okay i will try

2024-10-28 13:54 UTC, Subhajit-2023-44 commented
wait i will give a new PR soon

2024-10-28 18:46 UTC, closed without merging

2024-10-28 19:47 UTC, Subhajit-2023-44 commented
@Harshdev098 sir done 

![Screenshot 2024-10-29 011711](https://github.com/user-attachments/assets/fae1b0ac-cdfb-4d2f-882e-4e3a2cb2d429)