Corrected Misalignment of FAQs and Research Papers Section
Harshdev098/Research-Nexas pull request #315
Opened 2024-10-26 22:32 UTC by PrityanshuSingh

## 📋 Description

This PR addresses the alignment issue between the "Frequently Asked Questions" and "Our Research Papers" sections on the homepage. The purpose of this update is to enhance the visual layout by ensuring proper spacing and alignment between these two sections, leading to a cleaner and more organized appearance.

## 🔨 Changes Made

- Adjusted CSS styles to ensure proper alignment between the "Frequently Asked Questions" and "Our Research Papers" sections.
- Implemented responsive layout adjustments to maintain alignment across different screen sizes.

Fixes #279 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] I have followed all the guidelines mentioned in `CONTRIBUTING.md`.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] UI enhancement (non-breaking change which enhances UI) 🎨

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/0ac9485e-02fd-4d51-a56d-b459df437e21

2024-10-27 17:59 UTC, Harshdev098 requested changes

2024-10-27 17:59 UTC, Harshdev098 commented on public/css/style.css
> +  height: 100vh;
Just remove the height from here, it will be fixed

2024-10-29 11:15 UTC, PrityanshuSingh commented
@Harshdev098 Could you please let me know if there are any changes related to this PR, if not kindly please merge it, so that i can start working on other remaining issues.

2024-10-29 13:29 UTC, Harshdev098 commented on public/css/style.css
> +  height: 100vh;
> Just remove the height from here, it will be fixed

??

2024-10-29 14:12 UTC, PrityanshuSingh commented on public/css/style.css
> +  height: 100vh;
> from here, it will be fixed

@Harshdev098 My bad, didnt saw the comment, getting it done asap.

2024-10-29 19:42 UTC, PrityanshuSingh commented on public/css/style.css
> +  height: 100vh;
> > Just remove the height from here, it will be fixed
> 
> ?? @PrityanshuSingh

@Harshdev098 Just removed the height from there, and tested the code, it is working as expected. Kindly review and merge the PR.

2024-10-30 05:27 UTC, PrityanshuSingh commented
@Harshdev098 I have updated the code as per your suggestion, kindly merge the PR because today is the last day for gssoc-ext contributions.

2024-10-30 07:10 UTC, merged