Added otp based forgot password implementation
Harshdev098/Research-Nexas pull request #411
Opened 2024-11-08 12:27 UTC by Sourabh782

## 📋 Description

## 🔨 Changes Made

- Implemented otp based password reset functionality
- Added routes for otp verification and password reset
- Improved some bugs

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] I have followed all the guidlines mentioned in CONTRIBUTING.md.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #359 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/076f5a1a-caa3-4b63-9e45-8d5d6fc5668e

---

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

2024-11-08 15:26 UTC, Harshdev098 requested changes

2024-11-08 15:26 UTC, Harshdev098 commented on login-system/otp.js
> +                const transporter = nodemailer.createTransport({
instead duplicating the feature code just use it from the notification.js file

2024-11-08 15:48 UTC, Sourabh782 commented on login-system/otp.js
> +                const transporter = nodemailer.createTransport({
Sorry for the issue, i have fixed it

2024-11-09 03:48 UTC, Harshdev098 approved these changes

2024-11-09 03:48 UTC, merged

2024-11-09 12:56 UTC, Sourabh782 commented
hey @Harshdev098 can you please add labels, else it wont get counted. Thanks  :)