Enhanced header visibility and improved student section layout
Harshdev098/Research-Nexas pull request #92
Opened 2024-10-11 15:32 UTC by Shweta-1902

## 📋 Description

This pull request enhances the visibility of the header to prevent text from fading, ensuring a better user experience. Additionally, I've made several improvements to the student section layout, including better use of background colors and more detailed content for each student.

## 🔨 Changes Made

Improved header visibility to enhance text clarity and readability.
Enhanced the student section layout to ensure it occupies the entire box.
Increased the content for each student profile to fill the designated area effectively.
Updated images for student profiles with valid links.
Adjusted the overall styling for a more cohesive and appealing appearance.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

 I have followed all the guidelines mentioned in CONTRIBUTING.md.
 My code follows the style guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly in hard-to-understand areas.
 I have made corresponding changes to the documentation (if applicable).
 I have tested it locally and it works fine.
 Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

 UI enhancement (non-breaking change which enhances UI) 🎨

- Fixes #76 

## 📸 Screenshots (if applicable)

![Screenshot (414)](https://github.com/user-attachments/assets/b4d1cdff-446d-4351-aa51-367876f510ca)
![Screenshot (415)](https://github.com/user-attachments/assets/6b350a27-fd29-4466-a6a0-d1d38612ab33)
![Screenshot (416)](https://github.com/user-attachments/assets/a2180b4f-83ad-4e97-9493-c03dd5c92f92)
![Screenshot (419)](https://github.com/user-attachments/assets/d725541e-aa73-4b6f-8c73-3e810941cdaf)
![Screenshot (418)](https://github.com/user-attachments/assets/e99070fe-1a02-480a-80aa-12d64cfa5309)
![Screenshot (420)](https://github.com/user-attachments/assets/1a413f2b-ab5d-431a-b001-d4af38b143c8)
![Screenshot (422)](https://github.com/user-attachments/assets/a760c685-527f-48c8-9ed6-83d721abfe1c)

*Thank you for contributing to Research Nexus! We look forward to reviewing your PR and getting it merged!*

2024-10-11 20:00 UTC, Shweta-1902 commented
changes done

2024-10-12 03:36 UTC, Harshdev098 requested changes

2024-10-12 03:36 UTC, Harshdev098 commented on public/index.html
> +                navbar.style.backgroundColor = "rgba(0, 0, 0, 0.8)"; // Revert back to light background
make the backgroundColor none, it will be good

2024-10-12 03:53 UTC, Shweta-1902 commented
done but again the text almost gets invisible on white background

2024-10-12 03:58 UTC, Harshdev098 commented
I have requested to change only the else condition backgroundColor to be none, you have made backgroundColor none to both the conditions

2024-10-12 04:00 UTC, Harshdev098 commented
Just wait a minute, will give a solution to it

2024-10-12 04:03 UTC, Harshdev098 commented
Just make the backgroundColor to be transparent in the else condition, it will work @Shweta-1902

2024-10-12 04:21 UTC, Shweta-1902 commented
done

2024-10-12 04:26 UTC, Harshdev098 commented
Can you please your PR description, because it referencing this pr to the other PR but that should not be the case it should refer to the issue you have solved `fixes #<issue_number>`.
Will merge it

2024-10-12 04:27 UTC, merged

2024-10-12 05:33 UTC, Shweta-1902 commented
The leaderboard didn't got updated, it shows the same score as before

2024-10-12 05:35 UTC, Harshdev098 commented
It will be grt updated soon 
I have added the labels on the PR